### ISSUE TITLE
Autoupdation of csv

### ISSUE THREAD

**Issue by balajijagadesh** [rajeshkumargp/TamilWikisourceEbooksReportWebApp#2]
Hi..
    How is the export of logs.sqlite database with regard to Tamil into csv is done? 

The data found here is found to be static. does the numbers get updated automatically?
https://tools.wmflabs.org/shrinitools/TamilWikisourceEbooksReportWebApp/

**Comment by rajeshkumargp** [comment]
Hi Balaji, the export is done using sqlite package in Python. 
The data is static. But the data is updated for every hour as the code is scheduled as cron job.

**Comment by rajeshkumargp** [comment]
There should be Last Updated Field mentioning DATE AND TIME in the page.

**Comment by balajijagadesh** [comment]
Hi,
    When I went through the page it is observed that the page is not updated every hour by cron job. Please kindly look into this. 

Regards,
J. Balaji

**Comment by rajeshkumargp** [comment]
Let me check and update that.Thanks Balaji

**Comment by rajeshkumargp** [comment]
The code is updated so that the last updated time will be displayed in the Webpage. 
Thanks for info Balaji, It will be implemented soon.
